# Generated by Django 2.2.4 on 2019-09-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='kajnygren', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
