# Generated by Django 2.2.5 on 2019-09-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
