# Generated by Django 2.2.6 on 2019-11-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
