export const TRANSCODE_SEND_REQUEST = "TRANSCODE_SEND_REQUEST";
export const TRANSCODE_SEND_SUCCESS = "TRANSCODE_SEND_SUCCESS";
export const TRANSCODE_SEND_FAILURE = "TRANSCODE_SEND_FAILURE";
export const TRANSCODE_RESET = "TRANSCODE_RESET";